name: "HACS Validation"

on:
  push:
    tags:
      - "v*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
