# .github/workflows/validate.yml
name: Validate Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Normalize manifest.json
        run: |
          python3 - << 'EOF'
          import json
          from pathlib import Path

          mf = Path("custom_components/apex_monitor/manifest.json")
          data = json.loads(mf.read_text(encoding="utf-8"))

          # Build new object with correct order: domain, name, version, then alphabetical rest
          ordered = {
            "domain": data["domain"],
            "name": data["name"],
            "version": data["version"],
          }

          # Now add every other key in sorted order
          for k in sorted(k for k in data if k not in ordered):
              ordered[k] = data[k]

          # Write it back, 2-space indent, UTF-8 no BOM
          mf.write_text(json.dumps(ordered, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
          EOF

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
